### ISSUE TITLE
'Audio' & 'Transcripts' Pop-Up Window does not go away after clicking a link. Pop-Up Instead Stays in the background.

### ISSUE THREAD

**Issue by nowmichaelclark** [OpenSanghaFoundation/OSF#43]
**Describe the bug**
When clicking the 'Audio' or 'Transcripts' button, a pop-up appears. After clicking a link within the pop-up, the pop-up then disappears behind other windows but does not go away. This allows the pop-up to still consume resources for the user.

**To Reproduce**
1. Go to [https://opensanghafoundation.org/newsite/resources/](https://opensanghafoundation.org/newsite/resources/)
2. Click on the 'Audio' or 'Transcripts' button to Open Pop-Up Window.
![image](https://github.com/OpenSanghaFoundation/OSF/assets/162073748/bf45d5c0-37ad-4977-bdbf-8761fafa736e)
3. Click a link within the window that pops up.
4. See that the audio pop-up is still present but goes behind other windows.

**Expected behavior**
Audio pop-up closes after a link is clicked. This will save resources for the user's PC and make the overall experience cleaner. It's also worth noting: If a User has "open previously open tabs" enabled on their browser then the only window that will show after restarting their browser may be the Pop-up Window. This can happen from closing their main window first and then closing the Pop-up Window after.

**Video**
https://github.com/OpenSanghaFoundation/OSF/assets/162073748/0f055fe6-0989-48a6-a257-52fdee0f32b7

**Comment by OSFOSF** [comment]
generally we open as new page to allow the user to return to the page later. becuase of the way browser work not much resources are used. that especially ture becuase the audio generally takes them away from OSF

    On Friday, May 31, 2024 at 01:04:33 PM GMT+7, nowmichaelclark ***@***.***> wrote:  
 
 


Describe the bug
When clicking the "Audio" button, a pop-up appears. After clicking a link within the pop-up, the pop-up then disappears behind other windows but does not go away. This allows the pop-up to still consume resources for the user.

To Reproduce
Steps to reproduce the behavior:
   
   - Go to https://opensanghafoundation.org/newsite/resources/
   - Click on the 'Audio' button   
image.png (view on web)
   - Click a link within the window that pops up.
   - See that the audio pop-up is still present but goes behind other windows.

Expected behavior
Audio pop-up closes after a link is clicked. This will save resources for the user's PC and make the experience cleaner.

Screenshots
https://github.com/OpenSanghaFoundation/OSF/assets/162073748/d00d72bf-cb9e-4bfe-9226-599b7da3914d
