### ISSUE TITLE
Wordpress Does Not Allow Changing the Username of User's Profiles

### ISSUE THREAD

**Issue by nowmichaelclark** [OpenSanghaFoundation/OSF#51]
**Describe the bug**
When trying to change a User's username, this is not allowed. Wordpress blocks this from happening for already registered users.

**To Reproduce**
1. Go to [https://opensanghafoundation.org/newsite/user/canada+five+wisdoms+temple/?um_action=edit](https://opensanghafoundation.org/newsite/user/canada+five+wisdoms+temple/?um_action=edit)
2. Click on Username field
![image](https://github.com/OpenSanghaFoundation/OSF/assets/162073748/f04167ab-8502-41d7-9539-adaa589ef30b)
3. Type in a different name, Click update profile at the bottom of the page.
4. See that the username has not been updated.

**Expected behavior**
Typing in this box should change the username (or at least change the display name). If this name can not be changed or should not be changed then there is no reason to even show this text box as it will just confuse our volunteers who are doing data entry and may also confuse new users who are attempting to change their username/display name.

**Comment by coiby** [comment]
## Solution
1. [WP Admin panel -> Ultimate Member -> Settings -> Users -> User Display Name](https://opensanghafoundation.org/newsite/wp-admin/admin.php?page=um_options&section=users) -> Choose Nickname
![Screenshot_2024-07-10_21-01-13](https://github.com/OpenSanghaFoundation/OSF/assets/1511656/150c0dbc-2019-4d78-9540-c1a7c56e3561)
2. Add the pre-defined Nickname to the [profile form](https://opensanghafoundation.org/newsite/wp-admin/post.php?post=6165&action=edit) and change the label from Nickname to Name.
![Screenshot_2024-07-10_21-04-21](https://github.com/OpenSanghaFoundation/OSF/assets/1511656/439037de-e46d-4aa5-a37d-b1c97a3203c2)

## Analysis

Wordpress itself doesn't allow changing username but we can display an user's nickname instead. And there is no need to worry a nickname could be empty because 1) Wordpress takes the username as the initial value of nickname 2) If an user uses a different name for nickname, the nickname will be reset to the username if he/she uses an empty value.

**Comment by OSFOSF** [comment]
i have alredy checkd that every nickname is filled in will convert from display name slowly over time
    On Wednesday, July 10, 2024 at 08:38:11 PM GMT+7, Coiby ***@***.***> wrote:  
 
 


Solution
   
   - WP Admin panel -> Ultimate Member -> Settings -> Users -> User Display Name -> Choose Nickname   
Screenshot_2024-07-10_21-01-13.png (view on web)
   - Add the pre-defined Nickname to the profile form and change the label from Nickname to Name.   
Screenshot_2024-07-10_21-04-21.png (view on web)

Analysis

Wordpress itself doesn't allow changing username but we can display an user's nickname instead. And there is no need to worry a nickname could be empty because 1) Wordpress takes the username as the initial value of nickname 2) If an user uses a different name for nickname, the nickname will be reset to the username if he/she uses an empty value.

**Comment by OSFOSF** [comment]
uaing nickname
