### ISSUE TITLE
include/functions.php new warning 

### ISSUE THREAD

**Issue by OSFOSF** [OpenSanghaFoundation/OSF#58]
getting a new error on code that has been working for months.
Warning: file_get_contents(/home/u195962211/domains/opensanghafoundation.org/public_html/newsite/wp-content/plugins/xyz-wp-insert-code-snippet/shortcode-handler.php(296) : eval()'d code): failed to open stream: No such file or directory in /home/u195962211/domains/opensanghafoundation.org/public_html/newsite/wp-includes/functions.php on line 6864

this is my code line

if (wp_mail($to, $subject, $message, $headers, "-f .$From")) {

echo "<h3><b> EMAIL SENT SUCCESSFULLY </b></h3>" ;

and the warning comes from 6863-6869
function get_file_data( $file, $default_headers, $context = '' ) {
// Pull only the first 8 KB of the file in.
$file_data = file_get_contents( $file, false, null, 0, 8 * KB_IN_BYTES );

if ( false === $file_data ) {
$file_data = '';**Describe the bug**

this happens on all three pages, that send emails. But the email arrive correctly. 
An email has been sent to xyz about this warning.

**Comment by ttn-ttn** [comment]
The issue seems to be that `wp_mail($to, $subject, $message, $headers, "-f .$From")` actually means to call PHP's `mail` instead of Wordpress' `wp_mail`.

The Wordpress docs [describe wp_mail](https://developer.wordpress.org/reference/functions/wp_mail/) as `wp_mail( $to, $subject, $message, $headers, $attachments )`, where `$attachments` is an (optional) `array()`:

> The filenames in the $attachments attribute have to be filesystem paths

It's being passed `"-f .$From"` instead of an array of paths pointing to attachments. So it then tries to open a file called (e.g.) "youremail@yourdomain.com" as an attachment, fails, and generates the warning.

The solution would be to either change the call to use PHP `mail`, as seems to be the intention: `mail($to, $subject, $message, $headers, "-f .$From")`. Or, probably better, to fix the call to `wp_mail`: `wp_mail($to, $subject, $message, $headers)`.
